version: "3.8"


services:


#################################
# Database: The Database
#################################

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3302:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  
      MYSQL_DATABASE: inventory
    volumes:
     - ./db/inventory.sql:/docker-entrypoint-initdb.d/init.sql

#################################
# inventory: The inventory microservice
#################################


  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    image: ESDT8/inventory:1.0
    restart: always
    ports:
      - "5002:5000"
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3302/inventory