version: "3.8"

services:

#################################
# invoice: The invoice microservice
#################################

  invoice:
    build:
      context: ./invoice
      dockerfile: Dockerfile
    image: ESDT8/invoice:1.0
    restart: always
    ports:
      - "5007:5000"
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3307/invoice

#################################
# Database: The Database
#################################

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  
      MYSQL_DATABASE: invoice
    volumes:
     - ./db/invoice.sql:/docker-entrypoint-initdb.d/init.sql

